---
version: "3"
services:
  go-carbon:
    build: ./go-carbon
    volumes:
      - "./data/whisper:/var/lib/graphite/whisper"
  carbon-relay-ng:
    build: ./carbon-relay-ng
  carbonapi:
    build: ./carbonapi
  grafana:
    image: grafana/grafana
    env_file:
      - grafana-variables.env
    ports:
      - "3000:3000"
    volumes:
      - ./grafana/provisioning/:/etc/grafana/provisioning/
      - ./grafana/dashboards/:/var/lib/grafana/dashboards/
